name: CI

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install libraries
      run: npm install

    - name: Run tests
      run: npm run test
